name: Check apartments hourly

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install the Playwright test package (provides the 'playwright' CLI)
      - name: Install Playwright packages
        run: |
          npm install --no-audit --no-fund @playwright/test playwright

      # Install Chromium and required system deps (call CLI directly to avoid npx PATH issues)
      - name: Install Playwright browsers (Chromium + deps)
        run: |
          ./node_modules/.bin/playwright install --with-deps chromium

      # Run the scraper (renders JS, writes status.json and optional alerts)
      - name: Run scraper
        run: node scripts/check-apartments.playwright.mjs
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} # optional: set in repo secrets if you want notifications

      # Commit status.json if changed
      - name: Commit status.json if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add status.json
            git commit -m "Update apartment status (hourly)"
            git push
          fi

      # Upload debug artifacts (if any)
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-html-screens
          path: debug/
          if-no-files-found: ignore
